---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: image-build-listener
spec:
  serviceAccountName: tekton-robot
  triggers:
    - name: image-build-initiator
      bindings:
      - ref: image-build-binding
      template:
        ref: bootc-image-builder-trigger
      interceptors:
      - ref:
          name: cel
        params:
        - name: filter
          value: body['ref'].contains("qcow")
    - name: image-build-initiator
      bindings:
      - ref: image-build-binding
      template:
        ref: image-build-trigger
      interceptors:
      - ref:
          name: cel
        params:
        - name: filter
          value: "!(body['ref'].contains('qcow'))"
